name: Deploy Project (Update Only)

on:
  push:
    branches:
      - main

jobs:
  update_project:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update project on server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_HOST }}        # IP сервера
          username: ${{ secrets.SERVER_USER }}    # deploy_worker
          key: ${{ secrets.SSH_PRIVATE_KEY }}      # приватный ключ
          script: |
            cd /projects/api_work_for_everyone
            git pull
            docker-compose up -d --build

